// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package admin_role

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminRoleFieldNames          = builder.RawFieldNames(&AdminRole{})
	adminRoleRows                = strings.Join(adminRoleFieldNames, ",")
	adminRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(adminRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(adminRoleFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheHhOverseasAdminRoleIdPrefix = "cache:hhOverseas:adminRole:id:"
)

type (
	adminRoleModel interface {
		Insert(ctx context.Context, data *AdminRole) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AdminRole, error)
		Update(ctx context.Context, data *AdminRole) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAdminRoleModel struct {
		sqlc.CachedConn
		table string
	}

	AdminRole struct {
		Id         uint64    `db:"id"`
		RoleName   string    `db:"role_name"` // 角色名称
		Desc       string    `db:"desc"`      // 角色描述
		Status     int64     `db:"status"`    // 1启用  2关闭
		IsSuper    int64     `db:"is_super"`  // 超管标识 1：是 0：否
		CreateTime time.Time `db:"create_time"`
		UpdateTime time.Time `db:"update_time"`
		IsDeleted  int64     `db:"is_deleted"` // 1删除
	}
)

func newAdminRoleModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAdminRoleModel {
	return &defaultAdminRoleModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`admin_role`",
	}
}

func (m *defaultAdminRoleModel) Delete(ctx context.Context, id uint64) error {
	hhOverseasAdminRoleIdKey := fmt.Sprintf("%s%v", cacheHhOverseasAdminRoleIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, hhOverseasAdminRoleIdKey)
	return err
}

func (m *defaultAdminRoleModel) FindOne(ctx context.Context, id uint64) (*AdminRole, error) {
	hhOverseasAdminRoleIdKey := fmt.Sprintf("%s%v", cacheHhOverseasAdminRoleIdPrefix, id)
	var resp AdminRole
	err := m.QueryRowCtx(ctx, &resp, hhOverseasAdminRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminRoleModel) Insert(ctx context.Context, data *AdminRole) (sql.Result, error) {
	hhOverseasAdminRoleIdKey := fmt.Sprintf("%s%v", cacheHhOverseasAdminRoleIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, adminRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.RoleName, data.Desc, data.Status, data.IsSuper, data.IsDeleted)
	}, hhOverseasAdminRoleIdKey)
	return ret, err
}

func (m *defaultAdminRoleModel) Update(ctx context.Context, data *AdminRole) error {
	hhOverseasAdminRoleIdKey := fmt.Sprintf("%s%v", cacheHhOverseasAdminRoleIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.RoleName, data.Desc, data.Status, data.IsSuper, data.IsDeleted, data.Id)
	}, hhOverseasAdminRoleIdKey)
	return err
}

func (m *defaultAdminRoleModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheHhOverseasAdminRoleIdPrefix, primary)
}

func (m *defaultAdminRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminRoleModel) tableName() string {
	return m.table
}
