// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2

package types

type CreateRoleRequest struct {
	RoleName string `json:"role_name"`
	Desc     string `json:"desc"`
	Status   int    `json:"status"`
}

type CreateRoleResponse struct {
	Result bool `json:"result"`
}

type CreateUserRequest struct {
	UserName string `json:"user_name"`
	Account  string `json:"account"`
	Status   int    `json:"status"`
}

type CreateUserResponse struct {
	Result bool `json:"result"`
}

type GetRoleRequest struct {
	Id int64 `path:"roleId"`
}

type GetRoleResponse struct {
	RoleName string `json:"role_name"`
	Desc     string `json:"desc"`
	Status   int    `json:"status"`
	IsSuper  int    `json:"is_super"`
}

type GetUserRequest struct {
	Id int64 `path:"userId"`
}

type GetUserResponse struct {
	UserName string `json:"user_name"`
	Account  string `json:"account"`
	Status   int    `json:"status"`
}
