// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package admin_users

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminUsersFieldNames          = builder.RawFieldNames(&AdminUsers{})
	adminUsersRows                = strings.Join(adminUsersFieldNames, ",")
	adminUsersRowsExpectAutoSet   = strings.Join(stringx.Remove(adminUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminUsersRowsWithPlaceHolder = strings.Join(stringx.Remove(adminUsersFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheHhOverseasAdminUsersIdPrefix = "cache:hhOverseas:adminUsers:id:"
)

type (
	adminUsersModel interface {
		Insert(ctx context.Context, data *AdminUsers) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*AdminUsers, error)
		Update(ctx context.Context, data *AdminUsers) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultAdminUsersModel struct {
		sqlc.CachedConn
		table string
	}

	AdminUsers struct {
		Id            uint64         `db:"id"`
		UserName      string         `db:"user_name"`     // 名称
		Account       string         `db:"account"`       // 登录邮箱
		Password      sql.NullString `db:"password"`      // 密码
		Status        int64          `db:"status"`        // 1正常  2冻结
		WecomPhone    string         `db:"wecom_phone"`   // 企微手机号
		WecomUserId   string         `db:"wecom_user_id"` // 企业微信userid
		CreateTime    time.Time      `db:"create_time"`
		UpdateTime    time.Time      `db:"update_time"`
		LastLoginIp   string         `db:"last_login_ip"`   // 最近登录IP
		LastLoginTime sql.NullTime   `db:"last_login_time"` // 最近登录时间
		IsSupportIm   int64          `db:"is_support_im"`   // 是否支持im授权登陆
		IsDeleted     int64          `db:"is_deleted"`      // 1删除
	}
)

func newAdminUsersModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAdminUsersModel {
	return &defaultAdminUsersModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`admin_users`",
	}
}

func (m *defaultAdminUsersModel) Delete(ctx context.Context, id uint64) error {
	hhOverseasAdminUsersIdKey := fmt.Sprintf("%s%v", cacheHhOverseasAdminUsersIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, hhOverseasAdminUsersIdKey)
	return err
}

func (m *defaultAdminUsersModel) FindOne(ctx context.Context, id uint64) (*AdminUsers, error) {
	hhOverseasAdminUsersIdKey := fmt.Sprintf("%s%v", cacheHhOverseasAdminUsersIdPrefix, id)
	var resp AdminUsers
	err := m.QueryRowCtx(ctx, &resp, hhOverseasAdminUsersIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminUsersRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUsersModel) Insert(ctx context.Context, data *AdminUsers) (sql.Result, error) {
	hhOverseasAdminUsersIdKey := fmt.Sprintf("%s%v", cacheHhOverseasAdminUsersIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, adminUsersRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserName, data.Account, data.Password, data.Status, data.WecomPhone, data.WecomUserId, data.LastLoginIp, data.LastLoginTime, data.IsSupportIm, data.IsDeleted)
	}, hhOverseasAdminUsersIdKey)
	return ret, err
}

func (m *defaultAdminUsersModel) Update(ctx context.Context, data *AdminUsers) error {
	hhOverseasAdminUsersIdKey := fmt.Sprintf("%s%v", cacheHhOverseasAdminUsersIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminUsersRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.UserName, data.Account, data.Password, data.Status, data.WecomPhone, data.WecomUserId, data.LastLoginIp, data.LastLoginTime, data.IsSupportIm, data.IsDeleted, data.Id)
	}, hhOverseasAdminUsersIdKey)
	return err
}

func (m *defaultAdminUsersModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheHhOverseasAdminUsersIdPrefix, primary)
}

func (m *defaultAdminUsersModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", adminUsersRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminUsersModel) tableName() string {
	return m.table
}
